<#import "parts/common.ftlh" as c>

<@c.page>

<div style="
    background-image: url('https://source.unsplash.com/1600x900/?earth');
    background-size: cover;
    height: 100%;"
     class="jumbotron bg-dark text-white">
<div class="container">
    <p class="lead"> Tweee</p>
</div>
        </div>

<h5>Hello, world</h5>
<a href="/main">This is a twitter, based on Java Spring Boot</a>
        </@c.page>